<?xml version="1.0"?>
<robot name="ros_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Local Params -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.3"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.2"/>
  <xacro:property name="chassis_height" value="0.05"/>

  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <!-- Main Loom -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${chassis_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="wheel_left">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
              iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

<joint name="joint_wheel_left" type="continuous">
  <parent link="base_link"/>
  <child link="wheel_left"/>
  <origin xyz="${base_length/4} ${wheel_separation/3} -${chassis_height/2}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

  <!-- Right Wheel -->
  <link name="wheel_right">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
              iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="joint_wheel_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="${base_length/4} -${wheel_separation/3} -${chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Passive Back Wheels (caster) -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint_caster" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="-${base_length/2} 0 -0.025" rpy="0 0 0"/>
  </joint>

  <!-- Plugins -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=/odom</remapping>
      </ros>
      <commandTimeout>1.0</commandTimeout>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <wheelAcceleration>0.0</wheelAcceleration>
      <wheelTorque>5.0</wheelTorque>
      <updateRate>50.0</updateRate>
      <leftJoint>joint_wheel_left</leftJoint>
      <rightJoint>joint_wheel_right</rightJoint>
      <publishOdom>true</publishOdom>
      <odomFrame>odom</odomFrame>
      <odomTopic>odom</odomTopic>
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo>

</robot>
